// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw_6KUtKGr_q_ZccGsGo8M0SHC2aUdzD8',
    appId: '1:889670570373:web:88b54b90e591a8fad174ec',
    messagingSenderId: '889670570373',
    projectId: 'laksh-task',
    authDomain: 'laksh-task.firebaseapp.com',
    storageBucket: 'laksh-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4lYd44hnUTMhNsfDKVwGwRSWm9yH1fpI',
    appId: '1:889670570373:android:3a8c7916ef663e28d174ec',
    messagingSenderId: '889670570373',
    projectId: 'laksh-task',
    storageBucket: 'laksh-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgQR02uEmNBorL0HJuPahfsBMBvn-Ovlc',
    appId: '1:889670570373:ios:e52663914640d2fed174ec',
    messagingSenderId: '889670570373',
    projectId: 'laksh-task',
    storageBucket: 'laksh-task.appspot.com',
    iosBundleId: 'com.example.zylu',
  );
}
